/home/stud/m/mc085/mounted_home/dinov2/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/stud/m/mc085/mounted_home/dinov2/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/stud/m/mc085/mounted_home/dinov2/dinov2/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
submitit ERROR (2024-12-03 08:23:01,934) - Submitted job triggered an exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/submitit/core/submission.py", line 76, in submitit_main
    process_job(args.folder)
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/submitit/core/submission.py", line 69, in process_job
    raise error
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/submitit/core/submission.py", line 55, in process_job
    result = delayed.result()
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/submitit/core/utils.py", line 137, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/run/eval/knn.py", line 26, in __call__
    knn_main(self.args)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 381, in main
    eval_knn_with_model(
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 346, in eval_knn_with_model
    results_dict_knn = eval_knn(
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 300, in eval_knn
    _, results_dict = evaluate(model_with_knn, val_dataloader, postprocessors, metrics, device)
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/utils.py", line 67, in evaluate
    outputs = model(samples.to(device))
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 242, in forward
    return {k: module(*args, **kwargs) for k, module in self._modules.items()}
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 242, in <dictcomp>
    return {k: module(*args, **kwargs) for k, module in self._modules.items()}
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 242, in forward
    return {k: module(*args, **kwargs) for k, module in self._modules.items()}
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 242, in <dictcomp>
    return {k: module(*args, **kwargs) for k, module in self._modules.items()}
  File "/opt/miniconda3/envs/dinov2_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/stud/m/mc085/mounted_home/dinov2/dinov2/eval/knn.py", line 180, in forward
    one_hot(neighbors_labels, num_classes=self.num_classes),
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.88 GiB (GPU 0; 47.53 GiB total capacity; 2.47 GiB already allocated; 2.87 GiB free; 2.81 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
